<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
require_once (__DIR__ . '/../../../src/Helper/Constants.php');
include(__DIR__ . '/../config/config.php');
include_once(__DIR__ . '/../page/home.phtml');
include_once(__DIR__ . '/../page/menu.phtml');
include_once(__DIR__ . '/../page/events.phtml');
include_once(__DIR__ . '/../page/reviews.phtml');
include_once(__DIR__ . '/../page/foot.phtml');

?>